<?php

return [
    'uri' => env('COMMAND_UI_URI', '/command-ui'),
    'middleware' => env('COMMAND_UI_MIDDLEWARE', 'web'),
    'gate' => env('COMMAND_UI_GATE', 'command-ui'),
    'commands' => [
        'filter_list' => 'blacklist',
        'blacklist' => [
            ':work',
            '_',
            'about',
            'auth',
            'channel',
            'clear',
            'completion',
            'config:show',
            'db',
            'docs',
            'event',
            'help',
            'install',
            'invoke-serialized-closure',
            'key',
            'lang',
            'make:',
            'migrate',
            'model',
            'package',
            'schema',
            'serve',
            'storage',
            'stub',
            'test',
            'tinker',
            'vendor',
        ],
        'whitelist' => [
            'config:',
            'cache:',
            'route:',
        ],
    ],
];
